apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd-app-set
  namespace: argocd
spec:
  generators:
    - pullRequest: ## pull request
        github:
          owner: rayjang111 # 개인 id
          repo: gitops-cookbook-sc # repo
          labels:
            - preview # label 을 통해 pr 식별
        requeueAfterSeconds: 60
  template:
    metadata:
      name: bgd-{{branch}}-{{number}} # 생길 pod 이름
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rayjang111/gitops-cookbook-sc.git'
        targetRevision: '{{head_sha}}'
        path: ch08/bgd-pr
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{branch}}-{{number}}'
      syncPolicy:
        automated: # 자동 동기화 활성화
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true